Cypress.Commands.add('registerAndLoginUser', (testusername, testemail, testpassword) => {
    cy.session([testemail, testpassword], () => {
        cy.intercept('GET', '/').as('landingpage')
        cy.intercept('POST', '/register').as('register')
        cy.visit('/')
        cy.wait('@landingpage')
        cy.get('[data-testid="PersonIcon"]').click()
        cy.contains('button', 'Register').click()
        cy.get('#username').type(testusername)
        cy.get('#email').type(testemail)
        cy.get('#password').type(testpassword)
        cy.get('#confirmPassword').type(testpassword)
        cy.get('button[type="submit"]').click()
        cy.get('[data-cy="user"]').should('contain', testusername)
        cy.wait('@register')
    })
})
